nit: specific version command
0.1.0 doesn't exist so it fails, we also don't want to encourage users to install old versions so I left a placeholder. If they copy the placeholder and try it they'll get the informative error message:

error: invalid version format: latest (expected: X.Y.Z or X.Y.Z-pre)